version: '3.8'

services:
  # PostgreSQL Service
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_database
    ports:
      - "5432:5432"   # Expose PostgreSQL port to host
    volumes:
      - postgres-data:/var/lib/postgresql/data   # Persist data between container restarts

  # Redis Service
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"   # Expose Redis port to host

  # FastAPI Application Service
  fastapi:
    build: .
    container_name: fastapi
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"  # Expose FastAPI app port to host
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/auth_database
      REDIS_HOST: redis
    volumes:
      - .:/app  # Mount the current directory to /app in the container for code live updates (optional)

volumes:
  postgres-data:
