services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: auth_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # networks:
    #   - app-network
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    # networks:
    #   - app-network
  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_service
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/auth_database
      REDIS_HOST: redis
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    # networks:
    #   - app-network
volumes:
  postgres_data:
# networks:
#   app-network:
#     driver: bridge