version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres-container
    environment:
      POSTGRES_DB: auth_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: